version: '3.9'
services:
  mariadb:
    image: mariadb
    container_name: mariadb-2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: $MARIADB_DATABASE
      MYSQL_TCP_PORT: 3307
      MYSQL_UNIX_PORT: 3307
    ports:
      - "3307:3307"
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    container_name: phpmyadmin-2
    restart: always
    ports:
      - "8084:8082"
    environment:
      - DATABASE_PORT_NUMBER=3307
      - APACHE_HTTP_PORT_NUMBER=8082
    depends_on:
      - mariadb
  redis-2:
    image: bitnami/redis:latest
    container_name: redis-2
    restart: always
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_PORT_NUMBER: 6380
    ports:
      - "6380:6380"
  redisinsight-2:
    restart: always
    container_name: redisinsight-2
    image: redis/redisinsight:latest
    environment:
      RI_APP_PORT: 5541
    ports:
      - "5541:5541"
    depends_on:
      - redis-2
  medical-center-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-center-api
    volumes:
      - /tmp
    environment:
      SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MARIADB_ROOT_PASSWORD
      SPRING_DATA_REDIS_HOST: $DOCKER_REDIS_HOST
      SECURITY_JWT_SECRET: $JWT_SECRET
      SECURITY_JWT_ACCESS-TOKEN_EXPIRATION: $JWT_ACCESS_TOKEN_EXPIRATION
      SECURITY_JWT_REFRESH-TOKEN_EXPIRATION: $JWT_REFRESH_TOKEN_EXPIRATION
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - phpmyadmin
      - redis-2
      - redisinsight-2