apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configmap
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/otkisyan/medical-center-api.git'
      targetRevision: master
      path: k8s-stack/configmap 
  destination:
    name: "in-cluster"
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
