apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: loki 
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.30.1
      helm:
        valueFiles:
          - $values/k8s-stack/values/grafana-loki/values.yaml
    - repoURL: 'https://github.com/otkisyan/medical-center-api.git'
      targetRevision: master 
      ref: values
  destination:
    name: "in-cluster"
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
