apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: mariadb 
      repoURL: registry-1.docker.io/bitnamicharts  
      targetRevision: 20.5.9
      helm:
        valueFiles:
          - $values/k8s-stack/values/mariadb/values.yaml
    - repoURL: 'https://github.com/otkisyan/medical-center-api.git'
      targetRevision: master 
      ref: values
  destination:
    name: "in-cluster"
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
