spring:
  config:
    import: optional:file:.env.dev[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${MARIADB_ROOT_PASSWORD}
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  cache:
    type: redis
    redis:
      time-to-live: 30m
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6380
      password: ${REDIS_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  metrics:
    tags:
      application: medical-center-api
server:
  port: 8080
security:
  jwt:
    secret: ${JWT_SECRET}
    access-token:
      expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh-token:
      expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}