spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${HOST_SPRING_DATASOURCE_URL}
    username: root
    password: ${MARIADB_ROOT_PASSWORD}
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
server:
  port: 8080
security:
  jwt:
    secret: ${JWT_SECRET}
    access-token:
      expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh-token:
      expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}