apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root1
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: default 
  source:
    path   : "k8s-stack/argocd/apps"
    repoURL: "https://github.com/otkisyan/medical-center-api.git"
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
